### ISSUE TITLE
external browser login

### ISSUE THREAD

**Issue by buildorder** [atinfinity/sdk_manager_docker#10]
In sdk manager version 1.3.1.7110 should login to external browser

I tried install firefox and login in container, but I can't login
What could I do?

**Comment by TIS-Arne** [comment]
Installing `chromium-browser` worked for me.

**Comment by buildorder** [comment]
> Installing `chromium-browser` worked for me.

Thanks, It work!

**Comment by ltstein** [comment]
> > Installing `chromium-browser` worked for me.
> 
> Thanks, It work!

Install in the container or on the host? 

Edit: Installed in the container and it launched properly to complete login with Nvidia. May be something to add to the dockerfile.

**Comment by atinfinity** [comment]
@buildorder @TIS-Arne @ltstein Thank you for your report. I resolved in <https://github.com/atinfinity/sdk_manager_docker/pull/11>.
