### ISSUE TITLE
./launch_container.sh not working on mac

### ISSUE THREAD

**Issue by rmp58** [atinfinity/sdk_manager_docker#8]
when i ran ./launch_container.sh 
i got following error

./launch_container.sh: line 6: xauth: command not found
./launch_container.sh: line 6: xauth: command not found
./launch_container.sh: line 10: realpath: command not found
docker: Error response from daemon: Mounts denied:
The paths /Downloads and /nvidia
are not shared from OS X and are not known to Docker.
You can configure shared paths from Docker -> Preferences… -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
.
ERRO[0000] error waiting for container: context canceled

SO I CHANGED THE SHELL AS FOLLOWS 

#!/bin/sh

XSOCK=/tmp/.X11-unix
XAUTH=/tmp/.docker.xauth
touch $XAUTH
xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge -

mkdir -p jetpack_home/nvidia
mkdir -p jetpack_home/Downloads
JETPACK_HOME=$(realpath ./jetpack_home)

docker run --privileged --rm -it \
           --volume=/XSOCK:$XSOCK:rw \
           --volume=/XAUTH:$XAUTH:rw \
           --volume=/dev:/dev:rw \
           --volume=Users/Documents/Dockerfiles/sdk_manager_docker-master/jetpack_home/		            nvidia:/home/jetpack/nvidia:rw \
           --volume=Users/Documents/Dockerfiles/sdk_manager_docker-master/jetpack_home/			    Downloads:/home/jetpack/Downloads:rw \
           --shm-size=1gb \
           --env="XAUTHORITY=${XAUTH}" \
           --env="DISPLAY=${DISPLAY}" \
           --env=TERM=xterm-256color \
           --env=QT_X11_NO_MITSHM=1 \
           --net=host \
           -u "jetpack"  \
           jetpack:latest \
           bash

NOW I GET FOLLOWING ERROR

./launch_container.sh: line 6: xauth: command not found
./launch_container.sh: line 6: xauth: command not found
./launch_container.sh: line 10: realpath: command not found
docker: invalid reference format.
See 'docker run --help'.

**Comment by atinfinity** [comment]
@rmp58 I tested only Ubuntu PC as host machine.  
I set the following command to enable X Window System on Docker container.

> XSOCK=/tmp/.X11-unix
> XAUTH=/tmp/.docker.xauth
> touch $XAUTH
> xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge -

This page might be helpful to you.

- https://medium.com/@mreichelt/how-to-show-x11-windows-within-docker-on-mac-50759f4b65cb
- https://gist.github.com/cschiewek/246a244ba23da8b9f0e7b11a68bf3285
